# Generated by Django 3.2.5 on 2021-12-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication', models.CharField(default='', max_length=30, verbose_name='校验码')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10, verbose_name='问题类型')),
                ('title', models.CharField(default='', max_length=10, verbose_name='问题名称')),
                ('abstract', models.CharField(default='', max_length=50, verbose_name='问题摘要')),
                ('state', models.CharField(default='unsolved', max_length=10, verbose_name='问题状态')),
                ('question_time', models.DateTimeField(auto_now_add=True, verbose_name='提问时间')),
                ('is_star', models.BooleanField(default=False, verbose_name='是否加精')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('user_type', models.CharField(default='', max_length=12, verbose_name='用户类型')),
                ('username', models.CharField(default='', max_length=14, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=25, verbose_name='密码')),
                ('school', models.CharField(default='', max_length=13, verbose_name='学校')),
                ('img_url', models.CharField(default='', max_length=100, verbose_name='图片地址')),
                ('_class', models.CharField(default='', max_length=12, verbose_name='班级')),
                ('register_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10, verbose_name='回复类型')),
                ('content', models.CharField(default='', max_length=100, verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('poster_id', models.ForeignKey(db_column='poster_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.user')),
                ('question_id', models.ForeignKey(db_column='question_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='store.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answerer_id',
            field=models.ForeignKey(db_column='answerer_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='answerer_id', to='store.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner_id',
            field=models.ForeignKey(db_column='questioner_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questioner_id', to='store.user'),
        ),
        migrations.CreateModel(
            name='Picture_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(default='', upload_to='', verbose_name='图片地址')),
                ('reply_id', models.ForeignKey(db_column='reply_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_id', to='store.reply')),
            ],
        ),
    ]
