# Generated by Django 3.2.5 on 2021-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='authentication',
            field=models.CharField(default='', max_length=50, verbose_name='校验码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='abstract',
            field=models.CharField(default='', max_length=200, verbose_name='问题摘要'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='问题名称'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_class',
            field=models.CharField(default='', max_length=10, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(default='', max_length=100, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=15, verbose_name='学校'),
        ),
    ]
