# Generated by Django 3.2.5 on 2021-12-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerer_id',
            field=models.ForeignKey(db_column='answerer_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='answerer_id', to='store.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questioner_id',
            field=models.ForeignKey(db_column='questioner_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questioner_id', to='store.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='poster_id',
            field=models.ForeignKey(db_column='poster_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.question'),
        ),
    ]
